/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CameraAnchor")]
    [LuaRegisterType(0x8b7f8faf0110e39f, typeof(LuaBehaviour))]
    public class CameraAnchor : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "2a479195d1343f0489b6beb6e86c19a6";
        public override string ScriptGUID => s_scriptGUID;

        [Range(1,150)]
        [SerializeField] public System.Double _fieldOfView = 70;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _fieldOfView),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CameraAnchor/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
