/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/CameraTransitionType")]
    [LuaRegisterType(0xa700055de6a53c9d, typeof(LuaScriptableObject))]
    public class CameraTransitionType : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "f22133e84eb01b544ad9c21caf1de7e1";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _name = "NewType";
        [SerializeField] public UnityEngine.AnimationCurve _translationCurve = default;
        [SerializeField] public UnityEngine.AnimationCurve _rotationCurve = default;
        [SerializeField] public UnityEngine.AnimationCurve _zoomCurve = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _name),
                CreateSerializedProperty(_script.GetPropertyAt(1), _translationCurve),
                CreateSerializedProperty(_script.GetPropertyAt(2), _rotationCurve),
                CreateSerializedProperty(_script.GetPropertyAt(3), _zoomCurve),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CameraTransitionType/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
