/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/checkpointpopupui")]
    [LuaRegisterType(0xad2f5b7413379a65, typeof(LuaBehaviour))]
    public class checkpointpopupui : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "cd561e27481e50c42ba231605b097edf";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Message to display when a new check point is unlocked")]
        [SerializeField] public System.String _NewCheckPointMessage = "New Check Point Unlocked";
        [Tooltip("Duration of the flash")]
        [SerializeField] public System.Double _FlashDuration = 0.8;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _NewCheckPointMessage),
                CreateSerializedProperty(_script.GetPropertyAt(1), _FlashDuration),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/checkpointpopupui/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
