/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CheckPointDetector")]
    [LuaRegisterType(0xaded980d6f479cc5, typeof(LuaBehaviour))]
    public class CheckPointDetector : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b67e7fafafacecf4ba1bd7a6cc93e008";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("A unique identifier for the check point")]
        [SerializeField] public System.Double _CheckPointID = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _CheckPointID),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CheckPointDetector/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
