/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CinematicSequence")]
    [LuaRegisterType(0xe66f3ea9809d0a1f, typeof(LuaBehaviour))]
    public class CinematicSequence : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "24a8bea5fca849b419f62bb406920cc1";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("The cinematic camera that will play this cutscene")]
        [SerializeField] public UnityEngine.GameObject _targetCamera = default;
        [Tooltip("Should we try to play this cutscene as soon as its game object is enabled in the hierarchy?")]
        [SerializeField] public System.Boolean _playOnEnable = true;
        [Tooltip("Should the player be able to interact with taphandlers while this cutscene is active?")]
        [SerializeField] public System.Boolean _allowPlayerInput = false;
        [LuaScriptPropertyAttribute("f22133e84eb01b544ad9c21caf1de7e1")]
        [SerializeField] public UnityEngine.Object _defaultTransitionType = default;
        [LuaScriptPropertyAttribute("d94f2a267ce7ba44aa5223c534f2de0b")]
        [SerializeField] public UnityEngine.Object _defaultMaskType = default;
        [LuaScriptPropertyAttribute("9645d1880d43fcb4a9a6715b6384a4d5")]
        [SerializeField] public UnityEngine.Object _defaultFadeType = default;
        [LuaScriptPropertyAttribute("84d245359f87ad0418549450f68a0696")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> _events = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _targetCamera),
                CreateSerializedProperty(_script.GetPropertyAt(1), _playOnEnable),
                CreateSerializedProperty(_script.GetPropertyAt(2), _allowPlayerInput),
                CreateSerializedProperty(_script.GetPropertyAt(3), _defaultTransitionType),
                CreateSerializedProperty(_script.GetPropertyAt(4), _defaultMaskType),
                CreateSerializedProperty(_script.GetPropertyAt(5), _defaultFadeType),
                CreateSerializedProperty(_script.GetPropertyAt(6), _events),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CinematicSequence/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
