/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CinematicElements")]
    [LuaRegisterType(0x3b3544c190f4a68f, typeof(LuaBehaviour))]
    public class CinematicElements : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ace62632f805ab3409ffab265758033c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Animator m_Letterbox = default;
        [SerializeField] public UnityEngine.Animator m_TransitionsPanel = default;
        [SerializeField] public UnityEngine.GameObject m_maskRenderer = default;
        [SerializeField] public UnityEngine.GameObject m_fadePanel = default;
        [SerializeField] public UnityEngine.AnimationCurve _defaultFadeCurve = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Letterbox),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_TransitionsPanel),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_maskRenderer),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_fadePanel),
                CreateSerializedProperty(_script.GetPropertyAt(4), _defaultFadeCurve),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CinematicElements/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
