/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/devx_logger")]
    [LuaRegisterType(0xc8d44f91167dbb21, typeof(LuaBehaviour))]
    public class devx_logger : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "191444a0bc98ced4494b90518df1acf6";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Enable/Disable game logging")]
        [SerializeField] public System.Boolean _EnableGameLogging = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _EnableGameLogging),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/devx_logger/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
