/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/devx_config")]
    [LuaRegisterType(0xa449fed01b441f7b, typeof(LuaBehaviour))]
    public class devx_config : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1eae9b9a2bd0b1d48bbb5462b326f80b";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Used to identify currency products e.g. devx_currency_100")]
        [SerializeField] public System.String _CurrencyPrefix = "devx_currency";
        [Tooltip("Used to identify the currency storage key e.g. Currency")]
        [SerializeField] public System.String _StorageCurrencyKey = "Currency";
        [Tooltip("Used to identify the leaderboard storage key e.g. Leaderboard")]
        [SerializeField] public System.String _LeaderboardKey = "Leaderboard";
        [Tooltip("Used to identify the permissions storage key e.g. Permissions")]
        [SerializeField] public System.String _PermissionsStorageKey = "devx_permissions";
        [Tooltip("Used to identify the highest permission e.g. perm_superadmin")]
        [SerializeField] public System.String _HighestPermission = "perm_superadmin";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _CurrencyPrefix),
                CreateSerializedProperty(_script.GetPropertyAt(1), _StorageCurrencyKey),
                CreateSerializedProperty(_script.GetPropertyAt(2), _LeaderboardKey),
                CreateSerializedProperty(_script.GetPropertyAt(3), _PermissionsStorageKey),
                CreateSerializedProperty(_script.GetPropertyAt(4), _HighestPermission),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/devx_config/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
