/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/devx_events_factory")]
    [LuaRegisterType(0xb1960843071111d5, typeof(LuaBehaviour))]
    public class devx_events_factory : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "48765449b2f1c6f4ca562eaf936f5283";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Enable/Disable registry logging")]
        [SerializeField] public System.Boolean _EnableRegistyLogging = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _EnableRegistyLogging),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/devx_events_factory/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
