/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/devx_product_manager")]
    [LuaRegisterType(0x55d2c43e3d3014ac, typeof(LuaBehaviour))]
    public class devx_product_manager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6a06a2fafa596624d84ad4fb4ac52c6f";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Currency Icon")]
        [SerializeField] public UnityEngine.Texture _CurrencyIcon = default;
        [Tooltip("Deals Icons")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> _DealsIcons = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _CurrencyIcon),
                CreateSerializedProperty(_script.GetPropertyAt(1), _DealsIcons),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/devx_product_manager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
