/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/devx_audio_manager")]
    [LuaRegisterType(0x1d5427dcb5590b85, typeof(LuaBehaviour))]
    public class devx_audio_manager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1722ee4728765a74a9d3038326fdd8cb";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("List of audio shaders - starting index 1")]
        [SerializeField] public System.Collections.Generic.List<Highrise.AudioShader> _AudioShaders = default;
        [Tooltip("Enable/Disable SFX")]
        [SerializeField] public System.Boolean _EnableSFX = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _AudioShaders),
                CreateSerializedProperty(_script.GetPropertyAt(1), _EnableSFX),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/devx_audio_manager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
