/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/devx_storage_manager")]
    [LuaRegisterType(0x10479204f85618de, typeof(LuaBehaviour))]
    public class devx_storage_manager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b3a176c81cc0ba24fb57f80501a39fc4";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Whether to add a new entry to the storage if no value is found")]
        [SerializeField] public System.Boolean _RegisterPlayerStorageOnEmpty = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _RegisterPlayerStorageOnEmpty),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/devx_storage_manager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
