/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/devx_ui_manager")]
    [LuaRegisterType(0xd4b792386fb96e77, typeof(LuaBehaviour))]
    public class devx_ui_manager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ee164688ea66c1b49b541c97ca508e3a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean _EnableLogging = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _EnableLogging),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/devx_ui_manager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
