/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/FadeType")]
    [LuaRegisterType(0xdf1923fc31ca854b, typeof(LuaScriptableObject))]
    public class FadeType : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "9645d1880d43fcb4a9a6715b6384a4d5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AnimationCurve _fadeCurve = default;
        [SerializeField] public UnityEngine.Color _fadeColor = new Color(0f, 0f, 0f, 0f);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _fadeCurve),
                CreateSerializedProperty(_script.GetPropertyAt(1), _fadeColor),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/FadeType/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
