/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/mkUIManager")]
    [LuaRegisterType(0xe79fdf5c121210ae, typeof(LuaBehaviour))]
    public class mkUIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f8a493bb0c74d9f4ea5cd7377c03a87c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject _HUD = default;
        [SerializeField] public UnityEngine.GameObject _JoinButton = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _HUD),
                CreateSerializedProperty(_script.GetPropertyAt(1), _JoinButton),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/mkUIManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
