/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/panels")]
    [LuaRegisterType(0xa30a32310f338b02, typeof(LuaBehaviour))]
    public class panels : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d8f57c54b8f42a846904eca5e1c91edf";
        public override string ScriptGUID => s_scriptGUID;


        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
                CreateSerializedProperty(_script.GetPropertyAt(11), null),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
                CreateSerializedProperty(_script.GetPropertyAt(17), null),
                CreateSerializedProperty(_script.GetPropertyAt(18), null),
                CreateSerializedProperty(_script.GetPropertyAt(19), null),
                CreateSerializedProperty(_script.GetPropertyAt(20), null),
                CreateSerializedProperty(_script.GetPropertyAt(21), null),
                CreateSerializedProperty(_script.GetPropertyAt(22), null),
                CreateSerializedProperty(_script.GetPropertyAt(23), null),
                CreateSerializedProperty(_script.GetPropertyAt(24), null),
                CreateSerializedProperty(_script.GetPropertyAt(25), null),
                CreateSerializedProperty(_script.GetPropertyAt(26), null),
                CreateSerializedProperty(_script.GetPropertyAt(27), null),
                CreateSerializedProperty(_script.GetPropertyAt(28), null),
                CreateSerializedProperty(_script.GetPropertyAt(29), null),
                CreateSerializedProperty(_script.GetPropertyAt(30), null),
                CreateSerializedProperty(_script.GetPropertyAt(31), null),
                CreateSerializedProperty(_script.GetPropertyAt(32), null),
                CreateSerializedProperty(_script.GetPropertyAt(33), null),
                CreateSerializedProperty(_script.GetPropertyAt(34), null),
                CreateSerializedProperty(_script.GetPropertyAt(35), null),
                CreateSerializedProperty(_script.GetPropertyAt(36), null),
                CreateSerializedProperty(_script.GetPropertyAt(37), null),
                CreateSerializedProperty(_script.GetPropertyAt(38), null),
                CreateSerializedProperty(_script.GetPropertyAt(39), null),
                CreateSerializedProperty(_script.GetPropertyAt(40), null),
                CreateSerializedProperty(_script.GetPropertyAt(41), null),
                CreateSerializedProperty(_script.GetPropertyAt(42), null),
                CreateSerializedProperty(_script.GetPropertyAt(43), null),
                CreateSerializedProperty(_script.GetPropertyAt(44), null),
                CreateSerializedProperty(_script.GetPropertyAt(45), null),
                CreateSerializedProperty(_script.GetPropertyAt(46), null),
                CreateSerializedProperty(_script.GetPropertyAt(47), null),
                CreateSerializedProperty(_script.GetPropertyAt(48), null),
                CreateSerializedProperty(_script.GetPropertyAt(49), null),
                CreateSerializedProperty(_script.GetPropertyAt(50), null),
                CreateSerializedProperty(_script.GetPropertyAt(51), null),
                CreateSerializedProperty(_script.GetPropertyAt(52), null),
                CreateSerializedProperty(_script.GetPropertyAt(53), null),
                CreateSerializedProperty(_script.GetPropertyAt(54), null),
                CreateSerializedProperty(_script.GetPropertyAt(55), null),
                CreateSerializedProperty(_script.GetPropertyAt(56), null),
                CreateSerializedProperty(_script.GetPropertyAt(57), null),
                CreateSerializedProperty(_script.GetPropertyAt(58), null),
                CreateSerializedProperty(_script.GetPropertyAt(59), null),
                CreateSerializedProperty(_script.GetPropertyAt(60), null),
                CreateSerializedProperty(_script.GetPropertyAt(61), null),
                CreateSerializedProperty(_script.GetPropertyAt(62), null),
                CreateSerializedProperty(_script.GetPropertyAt(63), null),
                CreateSerializedProperty(_script.GetPropertyAt(64), null),
                CreateSerializedProperty(_script.GetPropertyAt(65), null),
                CreateSerializedProperty(_script.GetPropertyAt(66), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/panels/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
