/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PassCodeUI")]
    [LuaRegisterType(0xe70ff2b220803d03, typeof(LuaBehaviour))]
    public class PassCodeUI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f65d63e30fe7c4343b20969ca3383dc5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_PassKey = "";
        [SerializeField] public Highrise.AudioShader m_b1Audio = default;
        [SerializeField] public Highrise.AudioShader m_b2Audio = default;
        [SerializeField] public Highrise.AudioShader m_b3Audio = default;
        [SerializeField] public Highrise.AudioShader m_b4Audio = default;
        [SerializeField] public Highrise.AudioShader m_b5Audio = default;
        [SerializeField] public Highrise.AudioShader m_b6Audio = default;
        [SerializeField] public Highrise.AudioShader m_b7Audio = default;
        [SerializeField] public Highrise.AudioShader m_b8Audio = default;
        [SerializeField] public Highrise.AudioShader m_b9Audio = default;
        [SerializeField] public Highrise.AudioShader m_decAudio = default;
        [SerializeField] public Highrise.AudioShader m_appAudio = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_PassKey),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_b1Audio),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_b2Audio),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_b3Audio),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_b4Audio),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_b5Audio),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_b6Audio),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_b7Audio),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_b8Audio),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_b9Audio),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_decAudio),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_appAudio),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
                CreateSerializedProperty(_script.GetPropertyAt(17), null),
                CreateSerializedProperty(_script.GetPropertyAt(18), null),
                CreateSerializedProperty(_script.GetPropertyAt(19), null),
                CreateSerializedProperty(_script.GetPropertyAt(20), null),
                CreateSerializedProperty(_script.GetPropertyAt(21), null),
                CreateSerializedProperty(_script.GetPropertyAt(22), null),
                CreateSerializedProperty(_script.GetPropertyAt(23), null),
                CreateSerializedProperty(_script.GetPropertyAt(24), null),
                CreateSerializedProperty(_script.GetPropertyAt(25), null),
                CreateSerializedProperty(_script.GetPropertyAt(26), null),
                CreateSerializedProperty(_script.GetPropertyAt(27), null),
                CreateSerializedProperty(_script.GetPropertyAt(28), null),
                CreateSerializedProperty(_script.GetPropertyAt(29), null),
                CreateSerializedProperty(_script.GetPropertyAt(30), null),
                CreateSerializedProperty(_script.GetPropertyAt(31), null),
                CreateSerializedProperty(_script.GetPropertyAt(32), null),
                CreateSerializedProperty(_script.GetPropertyAt(33), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PassCodeUI/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
