/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Possessable")]
    [LuaRegisterType(0xba91303dc4ebea9b, typeof(LuaBehaviour))]
    public class Possessable : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b8bc4e82a5ed4dc45bf6f5b73b6ce313";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Identifier used for server-side disguise validation")]
        [SerializeField] public System.String m_propId = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_propId),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/Possessable/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
