/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PropHuntVFXManager")]
    [LuaRegisterType(0x8c4713bf55959ce6, typeof(LuaBehaviour))]
    public class PropHuntVFXManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "04a625fa75939cc4680039072c1259ba";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Duration for fade in animations")]
        [SerializeField] public System.Double _fadeInDuration = 0.3;
        [Tooltip("Duration for fade out animations")]
        [SerializeField] public System.Double _fadeOutDuration = 0.25;
        [Tooltip("Duration for scale pulse animations")]
        [SerializeField] public System.Double _pulseDuration = 0.4;
        [Tooltip("Duration for slide in animations")]
        [SerializeField] public System.Double _slideInDuration = 0.35;
        [Tooltip("Default easing for UI animations")]
        [SerializeField] public System.String _defaultEasing = "easeOutQuad";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _fadeInDuration),
                CreateSerializedProperty(_script.GetPropertyAt(1), _fadeOutDuration),
                CreateSerializedProperty(_script.GetPropertyAt(2), _pulseDuration),
                CreateSerializedProperty(_script.GetPropertyAt(3), _slideInDuration),
                CreateSerializedProperty(_script.GetPropertyAt(4), _defaultEasing),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PropHuntVFXManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
