/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PropHuntConfig")]
    [LuaRegisterType(0x6d68dac9b0c74897, typeof(LuaBehaviour))]
    public class PropHuntConfig : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a0ab8357b9247ad47b44d724a2ace8c1";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Time in seconds for the hiding phase")]
        [SerializeField] public System.Double _hidePhaseTime = 30;
        [Tooltip("Time in seconds for the hunting phase")]
        [SerializeField] public System.Double _huntPhaseTime = 120;
        [Tooltip("Time in seconds for the round end phase")]
        [SerializeField] public System.Double _roundEndTime = 10;
        [Tooltip("Minimum players required to start a round")]
        [SerializeField] public System.Double _minPlayersToStart = 2;
        [Tooltip("Enable debug logging")]
        [SerializeField] public System.Boolean _enableDebug = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _hidePhaseTime),
                CreateSerializedProperty(_script.GetPropertyAt(1), _huntPhaseTime),
                CreateSerializedProperty(_script.GetPropertyAt(2), _roundEndTime),
                CreateSerializedProperty(_script.GetPropertyAt(3), _minPlayersToStart),
                CreateSerializedProperty(_script.GetPropertyAt(4), _enableDebug),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PropHuntConfig/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
