/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PropHuntGameManager")]
    [LuaRegisterType(0xfc3f634c49d6491e, typeof(LuaBehaviour))]
    public class PropHuntGameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "65f089c15ccc03e439fd1c159cd0b660";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Time in seconds for the hiding phase")]
        [SerializeField] public System.Double _hidePhaseTime = 0;
        [Tooltip("Time in seconds for the hunting phase")]
        [SerializeField] public System.Double _huntPhaseTime = 0;
        [Tooltip("Time in seconds for the round end phase")]
        [SerializeField] public System.Double _roundEndTime = 0;
        [Tooltip("Minimum players required to start a round")]
        [SerializeField] public System.Double _minPlayersToStart = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _hidePhaseTime),
                CreateSerializedProperty(_script.GetPropertyAt(1), _huntPhaseTime),
                CreateSerializedProperty(_script.GetPropertyAt(2), _roundEndTime),
                CreateSerializedProperty(_script.GetPropertyAt(3), _minPlayersToStart),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PropHuntGameManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
