/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PropHuntLogger")]
    [LuaRegisterType(0x803c60637d153de5, typeof(LuaBehaviour))]
    public class PropHuntLogger : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "dc9d03ac08b229249bc33853a8c59247";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Enable/disable logging for GameManager")]
        [SerializeField] public System.Boolean _enableGameManager = true;
        [Tooltip("Enable/disable logging for PlayerManager")]
        [SerializeField] public System.Boolean _enablePlayerManager = true;
        [Tooltip("Enable/disable logging for ScoringSystem")]
        [SerializeField] public System.Boolean _enableScoringSystem = true;
        [Tooltip("Enable/disable logging for Teleporter")]
        [SerializeField] public System.Boolean _enableTeleporter = true;
        [Tooltip("Enable/disable logging for VFXManager")]
        [SerializeField] public System.Boolean _enableVFXManager = true;
        [Tooltip("Enable/disable logging for ZoneManager")]
        [SerializeField] public System.Boolean _enableZoneManager = true;
        [Tooltip("Enable/disable logging for UIManager")]
        [SerializeField] public System.Boolean _enableUIManager = true;
        [Tooltip("Enable/disable logging for HunterTagSystem")]
        [SerializeField] public System.Boolean _enableHunterTagSystem = true;
        [Tooltip("Enable/disable logging for PropPossessionSystem")]
        [SerializeField] public System.Boolean _enablePropPossessionSystem = true;
        [Tooltip("Enable/disable logging for PropDisguiseSystem - Not Implemented")]
        [SerializeField] public System.Boolean _enablePropDisguiseSystem_NotImplemented = true;
        [Tooltip("Enable/disable logging for RangeIndicator - Not Implemented")]
        [SerializeField] public System.Boolean _enableRangeIndicator_NotImplemented = false;
        [Tooltip("Enable/disable logging for ReadyButton - Not Implemented")]
        [SerializeField] public System.Boolean _enableReadyButton_NotImplemented = false;
        [Tooltip("Enable/disable logging for SpectatorButton - Not Implemented")]
        [SerializeField] public System.Boolean _enableSpectatorButton_NotImplemented = false;
        [Tooltip("Enable/disable logging for RecapScreen - Not Implemented")]
        [SerializeField] public System.Boolean _enableRecapScreen_NotImplemented = true;
        [Tooltip("Enable/disable logging for HUD - Not Implemented")]
        [SerializeField] public System.Boolean _enableHUD_NotImplemented = false;
        [Tooltip("Enable/disable logging for Config")]
        [SerializeField] public System.Boolean _enableConfig = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _enableGameManager),
                CreateSerializedProperty(_script.GetPropertyAt(1), _enablePlayerManager),
                CreateSerializedProperty(_script.GetPropertyAt(2), _enableScoringSystem),
                CreateSerializedProperty(_script.GetPropertyAt(3), _enableTeleporter),
                CreateSerializedProperty(_script.GetPropertyAt(4), _enableVFXManager),
                CreateSerializedProperty(_script.GetPropertyAt(5), _enableZoneManager),
                CreateSerializedProperty(_script.GetPropertyAt(6), _enableUIManager),
                CreateSerializedProperty(_script.GetPropertyAt(7), _enableHunterTagSystem),
                CreateSerializedProperty(_script.GetPropertyAt(8), _enablePropPossessionSystem),
                CreateSerializedProperty(_script.GetPropertyAt(9), _enablePropDisguiseSystem_NotImplemented),
                CreateSerializedProperty(_script.GetPropertyAt(10), _enableRangeIndicator_NotImplemented),
                CreateSerializedProperty(_script.GetPropertyAt(11), _enableReadyButton_NotImplemented),
                CreateSerializedProperty(_script.GetPropertyAt(12), _enableSpectatorButton_NotImplemented),
                CreateSerializedProperty(_script.GetPropertyAt(13), _enableRecapScreen_NotImplemented),
                CreateSerializedProperty(_script.GetPropertyAt(14), _enableHUD_NotImplemented),
                CreateSerializedProperty(_script.GetPropertyAt(15), _enableConfig),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PropHuntLogger/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
