/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PropHuntUIManager")]
    [LuaRegisterType(0x9f0d7b38b79658ea, typeof(LuaBehaviour))]
    public class PropHuntUIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4713727bf26fa3d44b60ddea26d4eb3a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject _HUD = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _HUD),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PropHuntUIManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
