/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SceneSwitcher")]
    [LuaRegisterType(0x5b8042647213c220, typeof(LuaBehaviour))]
    public class SceneSwitcher : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "edfe6b8cc772e45e2a2ddc8c1003de1a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_buttonIcon = default;
        [Tooltip("Name of the scene you want to teleport to")]
        [SerializeField] public System.String m_sceneName = "''";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_buttonIcon),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_sceneName),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/SceneSwitcher/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
