/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SpectatorToggleTest")]
    [LuaRegisterType(0xa0b812593372f942, typeof(LuaBehaviour))]
    public class SpectatorToggleTest : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1e0deff378db4b442a7551ce54e1c27c";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Drag the SpectatorToggle GameObject here")]
        [SerializeField] public UnityEngine.GameObject m_spectatorUIGameObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_spectatorUIGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/SpectatorToggleTest/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
