/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TipJarUtility")]
    [LuaRegisterType(0x5dbe2d5f396e2829, typeof(LuaBehaviour))]
    public class TipJarUtility : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "22f5db7e706abff4aa758b58f099e35d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _creatorName = "iHsein";
        [Tooltip("The limit of top tippers to show")]
        [Range(1,100)]
        [SerializeField] public System.Double _TopTippersLimit = 30;
        [Tooltip("The limit of tipping messages to show")]
        [Range(1,100)]
        [SerializeField] public System.Double _TippingMessagesLimit = 30;
        [SerializeField] public UnityEngine.GameObject _tipJarDrawer = default;
        [SerializeField] public UnityEngine.GameObject _tipJarBasic = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _creatorName),
                CreateSerializedProperty(_script.GetPropertyAt(1), _TopTippersLimit),
                CreateSerializedProperty(_script.GetPropertyAt(2), _TippingMessagesLimit),
                CreateSerializedProperty(_script.GetPropertyAt(3), _tipJarDrawer),
                CreateSerializedProperty(_script.GetPropertyAt(4), _tipJarBasic),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TipJarUtility/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
