/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TipJarTapper")]
    [LuaRegisterType(0x61c4de825d36e89b, typeof(LuaBehaviour))]
    public class TipJarTapper : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "66c0fc48b6137924080324f044e2e949";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("The main UI for the tip jar")]
        [SerializeField] public UnityEngine.GameObject _TipJarUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _TipJarUI),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TipJarTapper/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
