/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TipJarManager")]
    [LuaRegisterType(0xa15b1ddded249542, typeof(LuaBehaviour))]
    public class TipJarManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a3eeea3190d30f144a45b3618d181747";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("If enabled, an audio will play when a tip is received")]
        [SerializeField] public System.Boolean m_PlayAudioOnTip = false;
        [Tooltip("Anything lower than this amount will not be announced")]
        [SerializeField] public System.Double m_MinimumAnnouncementAmount = 100;
        [Tooltip("The announcement UI to display the tip")]
        [SerializeField] public UnityEngine.GameObject _TipJarAnnouncement = default;
        [Tooltip("The audio to play when a tip is received")]
        [SerializeField] public Highrise.AudioShader _TipRecievedSound = default;
        [Tooltip("The audio volume to play the tip sound")]
        [Range(0,1)]
        [SerializeField] public System.Double _AudioVolume = 0.5;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_PlayAudioOnTip),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_MinimumAnnouncementAmount),
                CreateSerializedProperty(_script.GetPropertyAt(2), _TipJarAnnouncement),
                CreateSerializedProperty(_script.GetPropertyAt(3), _TipRecievedSound),
                CreateSerializedProperty(_script.GetPropertyAt(4), _AudioVolume),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TipJarManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
