/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TriggerObjectToEnable")]
    [LuaRegisterType(0x5f3d3b1973e4801a, typeof(LuaBehaviour))]
    public class TriggerObjectToEnable : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1ba781f50cde0ee41b740ea830971ef7";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("If true, the mesh will be enabled/disabled on all clients")]
        [SerializeField] public System.Boolean _Syncronize = false;
        [Tooltip("If true, the mesh will be hidden by default and show when triggered")]
        [SerializeField] public System.Boolean _HideOnStart = true;
        [Tooltip("If true, the sound effect will be played when the trigger is activated")]
        [SerializeField] public System.Boolean _PlaySoundEffect = false;
        [Tooltip("The sound effect to play when the trigger is activated")]
        [SerializeField] public UnityEngine.AudioClip _SoundEffect = default;
        [Tooltip("The volume of the sound effect")]
        [Range(0,1)]
        [SerializeField] public System.Double _Volume = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _Syncronize),
                CreateSerializedProperty(_script.GetPropertyAt(1), _HideOnStart),
                CreateSerializedProperty(_script.GetPropertyAt(2), _PlaySoundEffect),
                CreateSerializedProperty(_script.GetPropertyAt(3), _SoundEffect),
                CreateSerializedProperty(_script.GetPropertyAt(4), _Volume),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TriggerObjectToEnable/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
