/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UITapperExample")]
    [LuaRegisterType(0x741942d03453b643, typeof(LuaBehaviour))]
    public class UITapperExample : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a38b469688357b547a963f728589b14a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject _UIPanels = default;
        [SerializeField] public System.String _Type = "Progress";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _UIPanels),
                CreateSerializedProperty(_script.GetPropertyAt(1), _Type),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/UITapperExample/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
