/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UnitySceneSetup")]
    [LuaRegisterType(0x4eef0306e9e2fde7, typeof(LuaBehaviour))]
    public class UnitySceneSetup : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c42131e172f8f8a4c8a12bddd0b45090";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_autoSetup = false;
        [SerializeField] public System.Boolean m_createExampleProps = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_autoSetup),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_createExampleProps),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/UnitySceneSetup/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
