/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/VFXSpawnTest")]
    [LuaRegisterType(0xf27263b470fc521a, typeof(LuaBehaviour))]
    public class VFXSpawnTest : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "52faa758f0325f942b176336e1e43c42";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Drag the ArenaSpawn GameObject here")]
        [SerializeField] public UnityEngine.GameObject m_arenaSpawnGameObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_arenaSpawnGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/VFXSpawnTest/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
