/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/world_config_config")]
    [LuaRegisterType(0x79a2f2d036f8b665, typeof(LuaBehaviour))]
    public class world_config_config : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d86dd2310d2171441ba024153daf4a78";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Storage key prefix for world configuration (e.g., 'WorldConfig')")]
        [SerializeField] public System.String _StorageKeyPrefix = "WorldConfig";
        [Tooltip("Whether to automatically create default configuration for new worlds")]
        [SerializeField] public System.Boolean _AutoCreateDefaults = true;
        [Tooltip("Whether to log all configuration operations for debugging")]
        [SerializeField] public System.Boolean _EnableLogging = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _StorageKeyPrefix),
                CreateSerializedProperty(_script.GetPropertyAt(1), _AutoCreateDefaults),
                CreateSerializedProperty(_script.GetPropertyAt(2), _EnableLogging),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/world_config_config/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
