/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/worldconfig")]
    [LuaRegisterType(0xf739689455d3f971, typeof(LuaBehaviour))]
    public class worldconfig : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3b5533293236e054e837dd1945890a55";
        public override string ScriptGUID => s_scriptGUID;


        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
                CreateSerializedProperty(_script.GetPropertyAt(11), null),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
                CreateSerializedProperty(_script.GetPropertyAt(17), null),
                CreateSerializedProperty(_script.GetPropertyAt(18), null),
                CreateSerializedProperty(_script.GetPropertyAt(19), null),
                CreateSerializedProperty(_script.GetPropertyAt(20), null),
                CreateSerializedProperty(_script.GetPropertyAt(21), null),
                CreateSerializedProperty(_script.GetPropertyAt(22), null),
                CreateSerializedProperty(_script.GetPropertyAt(23), null),
                CreateSerializedProperty(_script.GetPropertyAt(24), null),
                CreateSerializedProperty(_script.GetPropertyAt(25), null),
                CreateSerializedProperty(_script.GetPropertyAt(26), null),
                CreateSerializedProperty(_script.GetPropertyAt(27), null),
                CreateSerializedProperty(_script.GetPropertyAt(28), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/worldconfig/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
