/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ZoneVolume")]
    [LuaRegisterType(0x16cd4be9d5e43db1, typeof(LuaBehaviour))]
    public class ZoneVolume : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fb83cd6dbb2198547a27840462e3e644";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("Score multiplier for this zone (e.g., 1.5, 1.0, 0.6)")]
        [SerializeField] public System.Double m_zoneWeight = 1;
        [Tooltip("Enable debug logging for this zone")]
        [SerializeField] public System.Boolean m_enableDebug = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_zoneWeight),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_enableDebug),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/ZoneVolume/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
